import {createRouter, createWebHashHistory } from 'vue-router';

// CHEK IN
import MyPagesListInform from "@/pages/MyPagesListInform";
import MyPagesList1 from "@/pages/MyPagesList1";
import MyPagesList2 from "@/pages/MyPagesList2";
import MyPagesList3 from "@/pages/MyPagesList3";
import MyPagesList4 from "@/pages/MyPagesList4";
import MyPagesList5 from "@/pages/MyPagesList5";
import MyPagesList6 from "@/pages/MyPagesList6";
import MyPagesList7 from "@/pages/MyPagesList7";
import MyPagesList8 from "@/pages/MyPagesList8";
import MyPagesList9 from "@/pages/MyPagesList9";
import MyPagesList10 from "@/pages/MyPagesList10";
import MyPagesList11 from "@/pages/MyPagesList11";
import MyPagesList12 from "@/pages/MyPagesList12";
import MyPagesList13 from "@/pages/MyPagesList13";
import MyPagesList14 from "@/pages/MyPagesList14";
import MyPagesList15 from "@/pages/MyPagesList15";
import MyPagesList16 from "@/pages/MyPagesList16";
import MyPagesList17 from "@/pages/MyPagesList17";
import MyPagesList18 from "@/pages/MyPagesList18";
import MyPagesList19 from "@/pages/MyPagesList19";
import MyPagesList20 from "@/pages/MyPagesList20";
import MyPagesList21 from "@/pages/MyPagesList21";
import MyPagesList22 from "@/pages/MyPagesList22";
import MyPagesList23 from "@/pages/MyPagesList23";
import MyPagesList24 from "@/pages/MyPagesList24";
import MyPagesList25 from "@/pages/MyPagesList25";
import MyPagesList26 from "@/pages/MyPagesList26";
import MyPagesList27 from "@/pages/MyPagesList27";
import MyPagesList28 from "@/pages/MyPagesList28";
import MyPagesList29 from "@/pages/MyPagesList29";
import MyPagesList30 from "@/pages/MyPagesList30";
import MyPagesList31 from "@/pages/MyPagesList31";
import MyPagesList32 from "@/pages/MyPagesList32";
import MyPagesList33 from "@/pages/MyPagesList33";
import MyPagesList34 from "@/pages/MyPagesList34";
import MyPagesList35 from "@/pages/MyPagesList35";
import MyPagesList36 from "@/pages/MyPagesList36";
import MyPagesList37 from "@/pages/MyPagesList37";
import MyPagesList38 from "@/pages/MyPagesList38";
import MyPagesList39 from "@/pages/MyPagesList39";
import MyPagesList40 from "@/pages/MyPagesList40";
import MyPagesList41 from "@/pages/MyPagesList41";
import MyPagesList42 from "@/pages/MyPagesList42";
import MyPagesList43 from "@/pages/MyPagesList43";
import MyPagesList44 from "@/pages/MyPagesList44";
import MyPagesList45 from "@/pages/MyPagesList45";
import MyPagesList46 from "@/pages/MyPagesList46";
import MyPagesList47 from "@/pages/MyPagesList47";
import MyPagesList48 from "@/pages/MyPagesList48";
import MyPagesList49 from "@/pages/MyPagesList49";
import MyPagesList50 from "@/pages/MyPagesList50";
import MyPagesList51 from "@/pages/MyPagesList51";
import MyPagesList52 from "@/pages/MyPagesList52";
import MyPagesList53 from "@/pages/MyPagesList53";
import MyPagesList54 from "@/pages/MyPagesList54";
import MyPagesList55 from "@/pages/MyPagesList55";
import MyPagesList56 from "@/pages/MyPagesList56";
import MyPagesList57 from "@/pages/MyPagesList57";
import MyPagesList58 from "@/pages/MyPagesList58";
import MyPagesList59 from "@/pages/MyPagesList59";
import MyPagesList60 from "@/pages/MyPagesList60";
import MyPagesList61 from "@/pages/MyPagesList61";
import MyPagesList62 from "@/pages/MyPagesList62";
import MyPagesList63 from "@/pages/MyPagesList63";
import MyPagesList64 from "@/pages/MyPagesList64";
import MyPagesList65 from "@/pages/MyPagesList65";
import MyPagesList66 from "@/pages/MyPagesList66";
import MyPagesList67 from "@/pages/MyPagesList67";
import MyPagesList68 from "@/pages/MyPagesList68";
import MyPagesList69 from "@/pages/MyPagesList69";
import MyPagesList70 from "@/pages/MyPagesList70";
import MyPagesList71 from "@/pages/MyPagesList71";
import MyPagesList72 from "@/pages/MyPagesList72";

export default createRouter({
    history: createWebHashHistory(),
    routes:[
        // имя ссылки
        {path: '/1', component: MyPagesList1, alias: '/'},
        {path: '/2', component: MyPagesList2},
        {path: '/3', component: MyPagesList3},
        {path: '/4', component: MyPagesList4},
        {path: '/5', component: MyPagesList5},
        {path: '/6', component: MyPagesList6},
        {path: '/7', component: MyPagesList7},
        {path: '/8', component: MyPagesList8},
        {path: '/9', component: MyPagesList9},
        {path: '/10', component: MyPagesList10},
        {path: '/11', component: MyPagesList11},
        {path: '/12', component: MyPagesList12},
        {path: '/13', component: MyPagesList13},
        {path: '/14', component: MyPagesList14},
        {path: '/15', component: MyPagesList15},
        {path: '/16', component: MyPagesList16},
        {path: '/17', component: MyPagesList17},
        {path: '/18', component: MyPagesList18},
        {path: '/19', component: MyPagesList19},
        {path: '/20', component: MyPagesList20},
        {path: '/21', component: MyPagesList21},
        {path: '/22', component: MyPagesList22},
        {path: '/23', component: MyPagesList23},
        {path: '/24', component: MyPagesList24},
        {path: '/25', component: MyPagesList25},
        {path: '/26', component: MyPagesList26},
        {path: '/27', component: MyPagesList27},
        {path: '/28', component: MyPagesList28},
        {path: '/29', component: MyPagesList29},
        {path: '/30', component: MyPagesList30},
        {path: '/31', component: MyPagesList31},
        {path: '/32', component: MyPagesList32},
        {path: '/33', component: MyPagesList33},
        {path: '/34', component: MyPagesList34},
        {path: '/35', component: MyPagesList35},
        {path: '/36', component: MyPagesList36},
        {path: '/37', component: MyPagesList37},
        {path: '/38', component: MyPagesList38},
        {path: '/39', component: MyPagesList39},
        {path: '/40', component: MyPagesList40},
        {path: '/41', component: MyPagesList41},
        {path: '/42', component: MyPagesList42},
        {path: '/43', component: MyPagesList43},
        {path: '/44', component: MyPagesList44},
        {path: '/45', component: MyPagesList45},
        {path: '/46', component: MyPagesList46},
        {path: '/47', component: MyPagesList47},
        {path: '/48', component: MyPagesList48},
        {path: '/49', component: MyPagesList49},
        {path: '/50', component: MyPagesList50},
        {path: '/51', component: MyPagesList51},
        {path: '/52', component: MyPagesList52},
        {path: '/53', component: MyPagesList53},
        {path: '/54', component: MyPagesList54},
        {path: '/55', component: MyPagesList55},
        {path: '/56', component: MyPagesList56},
        {path: '/57', component: MyPagesList57},
        {path: '/58', component: MyPagesList58},
        {path: '/59', component: MyPagesList59},
        {path: '/60', component: MyPagesList60},
        {path: '/61', component: MyPagesList61},
        {path: '/62', component: MyPagesList62},
        {path: '/63', component: MyPagesList63},
        {path: '/64', component: MyPagesList64},
        {path: '/65', component: MyPagesList65},
        {path: '/66', component: MyPagesList66},
        {path: '/67', component: MyPagesList67},
        {path: '/68', component: MyPagesList68},
        {path: '/69', component: MyPagesList69},
        {path: '/70', component: MyPagesList70},
        {path: '/71', component: MyPagesList71},
        {path: '/72', component: MyPagesList72},
        {path: '/inform', component: MyPagesListInform},
    ]
})